// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ7HGzcgmuRYgkVUcv5CBiSy3RpJGW8UA',
    appId: '1:884443738158:android:3be2c35fd9242fdfa12fbf',
    messagingSenderId: '884443738158',
    projectId: 'quizz-app-a3e84',
    storageBucket: 'quizz-app-a3e84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhbYU9iy86eNDucYGlkXULqejm0q0OFIQ',
    appId: '1:884443738158:ios:8a58a3ad7b2634cda12fbf',
    messagingSenderId: '884443738158',
    projectId: 'quizz-app-a3e84',
    storageBucket: 'quizz-app-a3e84.firebasestorage.app',
    iosBundleId: 'com.oybek.quizzApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPQZcZgn3GJkaK5RHKsndy4_30glXMCzk',
    appId: '1:884443738158:web:55f6ae4fa0dd7a63a12fbf',
    messagingSenderId: '884443738158',
    projectId: 'quizz-app-a3e84',
    authDomain: 'quizz-app-a3e84.firebaseapp.com',
    storageBucket: 'quizz-app-a3e84.firebasestorage.app',
    measurementId: 'G-42XSCDSWER',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhbYU9iy86eNDucYGlkXULqejm0q0OFIQ',
    appId: '1:884443738158:ios:8a58a3ad7b2634cda12fbf',
    messagingSenderId: '884443738158',
    projectId: 'quizz-app-a3e84',
    storageBucket: 'quizz-app-a3e84.firebasestorage.app',
    iosBundleId: 'com.oybek.quizzApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPQZcZgn3GJkaK5RHKsndy4_30glXMCzk',
    appId: '1:884443738158:web:616448f29debfde9a12fbf',
    messagingSenderId: '884443738158',
    projectId: 'quizz-app-a3e84',
    authDomain: 'quizz-app-a3e84.firebaseapp.com',
    storageBucket: 'quizz-app-a3e84.firebasestorage.app',
    measurementId: 'G-KKRPRYTGVR',
  );

}